/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AlexT
 */
public class PokerTool extends javax.swing.JFrame {

    /**
     * Creates new form PokerTool
     */
    public PokerTool() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pokerToolTabbedPane = new javax.swing.JTabbedPane();
        addNewGamerFrame = new javax.swing.JInternalFrame();
        gamerNameLabel = new javax.swing.JLabel();
        newGamerNameTextField = new javax.swing.JTextField();
        addNewGamerButton = new javax.swing.JButton();
        javax.swing.JInternalFrame surchGamerInternalFrame = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        javax.swing.JTextField surchGamerTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        addNewInfoGamerInternalFrame = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addNewGamerFrame.setClosable(true);
        addNewGamerFrame.setVisible(true);

        gamerNameLabel.setText("Gamer name");

        addNewGamerButton.setText("Add new gamer");

        javax.swing.GroupLayout addNewGamerFrameLayout = new javax.swing.GroupLayout(addNewGamerFrame.getContentPane());
        addNewGamerFrame.getContentPane().setLayout(addNewGamerFrameLayout);
        addNewGamerFrameLayout.setHorizontalGroup(
            addNewGamerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewGamerFrameLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(gamerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newGamerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(addNewGamerButton)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        addNewGamerFrameLayout.setVerticalGroup(
            addNewGamerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewGamerFrameLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(addNewGamerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gamerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newGamerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNewGamerButton))
                .addContainerGap(398, Short.MAX_VALUE))
        );

        pokerToolTabbedPane.addTab("Add new gamer", addNewGamerFrame);

        surchGamerInternalFrame.setClosable(true);
        surchGamerInternalFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        surchGamerInternalFrame.setVisible(true);

        jLabel1.setText("Gamer name");

        jButton1.setText("Surch gamer");

        javax.swing.GroupLayout surchGamerInternalFrameLayout = new javax.swing.GroupLayout(surchGamerInternalFrame.getContentPane());
        surchGamerInternalFrame.getContentPane().setLayout(surchGamerInternalFrameLayout);
        surchGamerInternalFrameLayout.setHorizontalGroup(
            surchGamerInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(surchGamerInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(surchGamerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButton1)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        surchGamerInternalFrameLayout.setVerticalGroup(
            surchGamerInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(surchGamerInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(surchGamerInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surchGamerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(412, Short.MAX_VALUE))
        );

        pokerToolTabbedPane.addTab("Surch gamer", surchGamerInternalFrame);

        addNewInfoGamerInternalFrame.setClosable(true);
        addNewInfoGamerInternalFrame.setVisible(true);

        javax.swing.GroupLayout addNewInfoGamerInternalFrameLayout = new javax.swing.GroupLayout(addNewInfoGamerInternalFrame.getContentPane());
        addNewInfoGamerInternalFrame.getContentPane().setLayout(addNewInfoGamerInternalFrameLayout);
        addNewInfoGamerInternalFrameLayout.setHorizontalGroup(
            addNewInfoGamerInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        addNewInfoGamerInternalFrameLayout.setVerticalGroup(
            addNewInfoGamerInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pokerToolTabbedPane.addTab("Add new information to gamer", addNewInfoGamerInternalFrame);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pokerToolTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pokerToolTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );

        pokerToolTabbedPane.getAccessibleContext().setAccessibleName("Poker tool");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokerTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokerTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokerTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokerTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PokerTool().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewGamerButton;
    private javax.swing.JInternalFrame addNewGamerFrame;
    private javax.swing.JInternalFrame addNewInfoGamerInternalFrame;
    private javax.swing.JLabel gamerNameLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField newGamerNameTextField;
    private javax.swing.JTabbedPane pokerToolTabbedPane;
    // End of variables declaration//GEN-END:variables

}
