
import exception.*;
import gamer.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import mysql.gamer.*;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author AlexT
 */
public class PokerTool extends javax.swing.JFrame {

    /**
     * Creates new form PokerTool
     */
    public PokerTool() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchGamerName = new javax.swing.JTextField();
        searchGamerButton = new javax.swing.JButton();
        addGamerName = new javax.swing.JTextField();
        addGamerButton = new javax.swing.JButton();
        gamerNote = new java.awt.TextArea();
        addNoteButton = new javax.swing.JButton();
        addNewGamerNote = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchGamerButton.setText("Search gamer");
        searchGamerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchGamerButtonActionPerformed(evt);
            }
        });

        addGamerButton.setText("Add new gamer");
        addGamerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGamerButtonActionPerformed(evt);
            }
        });

        addNoteButton.setText("Add note");
        addNoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNoteButtonActionPerformed(evt);
            }
        });

        addNewGamerNote.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        addNewGamerNote.setForeground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addNoteButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gamerNote, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 161, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(searchGamerName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchGamerButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addGamerName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(addNewGamerNote, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(6, 6, 6)
                        .addComponent(addGamerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchGamerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchGamerButton)
                    .addComponent(addGamerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addGamerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addNewGamerNote, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(gamerNote, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNoteButton)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchGamerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchGamerButtonActionPerformed
        // TODO add your handling code here:
        if (searchGamerName.getText() != null || !searchGamerName.getText().equals("")) {
            String gamerName = searchGamerName.getText();
            System.out.println(gamerName);
            String dbmsConnString = "jdbc:mysql://localhost:3306/poker_tool_database";
            String userName = "root";
            String password = "SwiftTraining1";
            Gamer gamer = null;
            
            MySqlGamer mySqlGamer = new MySqlGamer(dbmsConnString, userName, password);
            try {
                gamer = mySqlGamer.getGamer(gamerName);
            } catch (DALException ex) {
                Logger.getLogger(PokerTool.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(PokerTool.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (gamer != null) {            
            MySqlPicture mySqlPicture = new MySqlPicture(dbmsConnString, userName, password);
                try {
                    gamer.setGamerNote(mySqlGamer.getNotes(gamer.getGamerId()));
                } catch (DALException ex) {
                    Logger.getLogger(PokerTool.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(PokerTool.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    gamer.setGamerPictures(mySqlPicture.getPictures(gamer.getGamerId()));
                } catch (DALException ex) {
                    Logger.getLogger(PokerTool.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(PokerTool.class.getName()).log(Level.SEVERE, null, ex);
                }
                gamerNote.setText(gamer.getGamerNote());
                addNewGamerNote.setText(gamerName);
        }
        }
    }//GEN-LAST:event_searchGamerButtonActionPerformed

    private void addNoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNoteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNoteButtonActionPerformed

    private void addGamerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGamerButtonActionPerformed
        // TODO add your handling code here:
        if (addGamerName.getText() != null || !addGamerName.getText().equals("")) {
            String gamerName = addGamerName.getText();
            String dbmsConnString = "jdbc:mysql://localhost:3306/poker_tool_database";
            String userName = "root";
            String password = "SwiftTraining1";

            MySqlGamer mySqlGamer = new MySqlGamer(dbmsConnString, userName, password);
            try {
                mySqlGamer.insertNewGamer(gamerName);
            } catch (DALException ex) {
                Logger.getLogger(PokerTool.class.getName()).log(Level.SEVERE, null, ex);
            }
            String text = gamerName + " is added!";
            //addNewGamerNote.setText(text);
            addGamerName.setText("");

        }
    }//GEN-LAST:event_addGamerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokerTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokerTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokerTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokerTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PokerTool().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGamerButton;
    private javax.swing.JTextField addGamerName;
    private javax.swing.JLabel addNewGamerNote;
    private javax.swing.JButton addNoteButton;
    private java.awt.TextArea gamerNote;
    private javax.swing.JButton searchGamerButton;
    private javax.swing.JTextField searchGamerName;
    // End of variables declaration//GEN-END:variables

}
